feat: whois command
ud-cis-discord/SageV2 pull request #100
Opened 2021-02-17 19:50 UTC by joshualyon7

2021-02-17 19:57 UTC, BenSegal855 requested changes

2021-02-17 19:57 UTC, BenSegal855 commented on src/commands/staff/whois.ts
> +	const roles = member.roles.cache.map(role => role.name).sort().join(', ');
```suggestion
	const roles = member.roles.cache.size > 1
		? member.roles.cache.filter(r => r.id !== r.guild.id).sort().array().join(' ')
		: 'none';
```
Removes the `@everyone` role and shows as mentions for *fun colors*

2021-02-17 19:57 UTC, BenSegal855 commented on src/commands/staff/whois.ts
> +	return userParser(msg, input);
```suggestion
export function argParser(msg: Message, input: string): Promise<Array<GuildMember>> {
	if (!input) {
		throw `Usage: ${usage}`;
	}
	return [userParser(msg, input)];
```
argParser should always return an array. ~~or a promise that resolves to an array~~

2021-02-17 19:57 UTC, BenSegal855 commented on src/commands/staff/whois.ts
> +export function run(msg: Message, member: GuildMember): Promise<Message> {
```suggestion
export function run(msg: Message, [member]: [GuildMember]): Promise<Message> {
```
See very last comment.

2021-02-19 21:20 UTC, BenSegal855 approved these changes

2021-02-19 21:21 UTC, renross approved these changes

2021-02-19 21:21 UTC, merged