Mention fix
ud-cis-discord/SageV2 pull request #142
Opened 2021-03-27 20:29 UTC by joshualyon7

2021-03-27 21:31 UTC, renross submitted a review, later dismissed

2021-03-27 23:16 UTC, BenSegal855 requested changes
In announce.ts, change the `channel.send()` options so that role/everyone pings can still happen in announcements.

2021-03-30 16:06 UTC, BenSegal855 approved these changes

2021-03-30 16:19 UTC, renross approved these changes

2021-03-30 16:19 UTC, merged