GitHub
ud-cis-discord/SageV2 pull request #144
Opened 2021-03-27 21:15 UTC by joshualyon7

2021-03-27 21:31 UTC, renross submitted a review, later dismissed

2021-03-27 23:23 UTC, BenSegal855 requested changes

2021-03-27 23:23 UTC, BenSegal855 commented on src/commands/admin/issue.ts
> +		milestone: milestone !== '' ? milestone : undefined,
Can probably be simplified to...
```suggestion
		milestone: milestone || undefined,
```

2021-03-27 23:23 UTC, BenSegal855 commented on src/sage.ts
> +import { DB, BOT, PREFIX, GITHUB_TOKEN } from '@root/config';
`GITHUB_TOKEN` should be added to the example config

2021-03-27 23:34 UTC, BenSegal855 approved these changes

2021-03-28 02:33 UTC, renross approved these changes

2021-03-28 02:33 UTC, merged