Doc automation
ud-cis-discord/SageV2 pull request #173
Opened 2021-04-20 16:05 UTC by joshualyon7

2021-04-20 16:15 UTC, BenSegal855 submitted a review, later dismissed

2021-04-20 16:24 UTC, BenSegal855 requested changes

2021-04-20 16:24 UTC, BenSegal855 commented on Jenkinsfile
> +						if(env.BRANCH_NAME == 'docAutomation') {
```suggestion
						if(env.BRANCH_NAME == env.MAIN_BRANCH) {
```

2021-04-20 16:26 UTC, BenSegal855 approved these changes

2021-04-21 02:47 UTC, renross approved these changes

2021-04-21 02:48 UTC, merged

2021-04-21 14:54 UTC, Enturk commented
Love.jpg