added better error handling for issue command (closes #172)
ud-cis-discord/SageV2 pull request #174
Opened 2021-04-20 17:26 UTC by joshualyon7

2021-04-20 17:35 UTC, BenSegal855 requested changes

2021-04-20 17:35 UTC, BenSegal855 commented on src/commands/admin/issue.ts
> +	let project = 'bot';
```suggestion
	let project = 'SageV2';
```

2021-04-20 17:38 UTC, BenSegal855 approved these changes

2021-04-21 02:47 UTC, renross approved these changes

2021-04-21 02:47 UTC, merged