add Admins to s;private threads
ud-cis-discord/SageV2 pull request #207
Opened 2021-09-17 04:54 UTC by renross

2021-09-17 11:43 UTC, BenSegal855 requested changes

2021-09-17 11:43 UTC, BenSegal855 commented on src/commands/partial visibality question/private.ts
> +		privThread.guild.members.cache.filter(mem => mem.roles.cache.has('808402548976517158')).forEach(user => {
Hard coding IDs is 👎, you should probably use a config value here.

2021-09-17 18:51 UTC, BenSegal855 approved these changes

2021-09-17 23:49 UTC, joshualyon7 requested changes

2021-09-17 23:49 UTC, joshualyon7 commented on src/commands/partial visibality question/private.ts
> +		privThread.guild.members.cache.filter(mem => mem.roles.cache.has(ROLES.STUDENT_ADMIN)).forEach(user => {
You could probably do this in one pass of the guild roles just by adding a `|| mem.roles.cache.has(ROLES.STUDENT_ADMIN)` to the previously existing filteron line 37

2021-09-18 15:58 UTC, joshualyon7 approved these changes

2021-09-18 15:59 UTC, joshualyon7 requested changes
Merge into dev instead

2021-09-18 16:27 UTC, joshualyon7 approved these changes

2021-09-18 16:27 UTC, merged