QT refactor
ud-cis-discord/SageV2 pull request #47
Opened 2021-01-20 04:16 UTC by BenSegal855

Closes #44. The `question` and `tagquestion` commands now take args in a much friendlier way utilizing course info from the context of the message. Also, collection names were moved to the config because I had to change one and it was a pain so I thought I would make it easier to change if necessary in the future.

2021-01-20 06:12 UTC, renross approved these changes

2021-01-20 12:16 UTC, joshualyon7 requested changes
Spelling stuff

2021-01-20 12:16 UTC, joshualyon7 commented on src/commands/configuration/addcourse.ts
> +export const description = 'Creates a corses category and adds all necessary channels/roles.';
```
Courses*
```

2021-01-20 12:16 UTC, joshualyon7 commented on src/commands/partial visibality question/anonymous.ts
> +			throw `I wasn't able to determine your course biased off of your enrollment or your input. Please specify the corse at the beginning of your question.
`based*` `course*`

2021-01-20 12:16 UTC, joshualyon7 commented on src/commands/partial visibality question/anonymous.ts
> +Available corses: \`${courses.map(c => c.name).join('`, `')}\``;
`courses*`

2021-01-20 12:16 UTC, joshualyon7 commented on src/commands/partial visibality question/private.ts
> +			throw `I wasn't able to determine your course biased off of your enrollment or your input. Please specify the corse at the beginning of your question.
`based*` `course*` (same string as before)

2021-01-20 12:16 UTC, joshualyon7 commented on src/commands/question tagging/question.ts
> +			throw 'I wasn\'t able to determine your course biased off of your enrollment or your input. Please specify the corse at the beginning of your question.' +
`course*`

2021-01-21 17:18 UTC, joshualyon7 approved these changes

2021-01-21 17:18 UTC, merged