Onboard update
ud-cis-discord/SageV2 pull request #53
Opened 2021-01-25 21:50 UTC by BenSegal855

2021-01-25 21:51 UTC, renross approved these changes

2021-01-25 21:52 UTC, joshualyon7 requested changes

2021-01-25 21:52 UTC, joshualyon7 commented on src/pieces/logs/serverLog.ts
> +	// console.log(inspect(logEntry, { depth: null }));
do we want this still here

2021-01-25 21:56 UTC, renross approved these changes

2021-01-26 20:58 UTC, joshualyon7 approved these changes

2021-01-26 21:05 UTC, renross approved these changes

2021-01-26 21:05 UTC, merged